# Generated by Django 4.2.7 on 2023-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Foto', models.ImageField(upload_to='images')),
            ],
        ),
    ]
