# Generated by Django 4.2.7 on 2023-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pedido_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='preco_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
