# Generated by Django 4.2.7 on 2023-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pedido_itens_precoxquantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo',
            field=models.CharField(choices=[('P', 'PIX'), ('C', 'CARTÃO'), ('B', 'BOLETO')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pedido',
            field=models.CharField(choices=[('E', 'Entregue'), ('C', 'Cancelado'), ('T', 'Transporte'), ('P', 'Preparação')], default='P', max_length=1),
        ),
    ]
